<?php

/**
 * @file
 * The main Islandora Metadata Extras module file.
 */

/**
 * Implements hook_menu().
 */
function islandora_metadata_extras_menu() {
  $items = array();
  $items['admin/islandora/tools/metadata_extras'] = array(
    'title' => 'Metadata Extras',
    'description' => 'Configure the Islandora Metadata Extras module.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('islandora_metadata_extras_admin_form'),
    'file' => 'includes/admin.form.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function islandora_metadata_extras_ctools_plugin_api($module, $api) {
  if ($module == 'qtip' && $api == 'qtip_default') {
    return array('version' => '1');
  }
}

/**
 * Implements hook_islandora_solr_object_result_alter().
 */
function islandora_metadata_extras_islandora_solr_object_result_alter(&$search_result, $query_processor) {
  if (variable_get('islandora_metadata_extras_use_collection_label', FALSE)) {
    module_load_include('inc', 'islandora_metadata_extras', 'includes/utilities');
    $collection_field = variable_get('islandora_solr_member_of_collection_field', 'RELS_EXT_isMemberOfCollection_uri_ms');
    if (isset($search_result['solr_doc'][$collection_field])) {
      foreach ($search_result['solr_doc'][$collection_field] as $collection_pid) {
        $search_result['solr_doc'][$collection_field] = islandora_metadata_extras_pid_to_label($collection_pid);
      }
    }
  }
}

/**
 * Implements hook_islandora_view_object_alter().
 */
function islandora_metadata_extras_islandora_view_object_alter(&$object, &$rendered) {
  if (variable_get('islandora_metadata_extras_hide_empty_metadata_values', FALSE)) {
    drupal_add_js(drupal_get_path('module', 'islandora_metadata_extras') . '/js/hide_empty_metadata_values.js', 'file');
  }

  if (variable_get('islandora_metadata_extras_show_pretty_dates', FALSE)) {
    global $language;
    drupal_add_js(array('islandora_metadata_extras' => array('locale' => $language->language)), array('type' => 'setting'));
    drupal_add_js(drupal_get_path('module', 'islandora_metadata_extras') . '/js/convert_date_values.js', 'file');
  }
}

/**
 * Theme preprocess function.
 */
function islandora_metadata_extras_preprocess_islandora_solr_wrapper(&$variables) {
  if (variable_get('islandora_metadata_extras_hide_empty_values_in_search_results', FALSE)) {
    drupal_add_js(drupal_get_path('module', 'islandora_metadata_extras') . '/js/hide_empty_values_in_search_results.js', 'file');
  }
  if (variable_get('islandora_metadata_extras_show_tooltips_in_search_results', FALSE)) {
    $preview_markup = '<div style="display: none;" class="qtipcontent" data-qtip-instance="islandora_metadata_extras_preview">I am some markup yo</div>';
    drupal_add_js(array('islandora_metadata_extras' => array('tooltip_markup' => $preview_markup)), array('type' => 'setting'));
    drupal_add_js(drupal_get_path('module', 'islandora_metadata_extras') . '/js/show_metadata_previews.js', 'file');
  }
}

function islandora_metadata_extras_preprocess_islandora_solr(&$variables) {
  // Called once for search results page, doesn't provide access to individual results.
}

/**
 * Implements hook_islandora_datastream_alter().
 */
function islandora_metadata_extras_islandora_datastream_alter($object, $datastream, &$context) {
  if (variable_get('islandora_metadata_extras_add_uuid_to_mods', FALSE)) {
    if ($object['MODS'] && $datastream->id == 'MODS' && $context['action'] == 'ingest') {
      // Check to see if we already have an identifier element with type
      // 'uuid' and if not, add one.
      $dom = new DOMDocument();
      $dom->loadXML($datastream->content);
      $xpath = new DOMXPath($dom);
      $xpath->registerNamespace('mods', 'http://www.loc.gov/mods/v3');
      $existing_uuid_identifiers = $xpath->query("//mods:identifier[@type='uuid']");
      if ($existing_uuid_identifiers->length === 0) {
        module_load_include('inc', 'islandora_metadata_extras', 'includes/utilities');
        if ($with_uuid = islandora_metadata_extras_add_uuid_to_mods($object->id, $datastream->content)) {
          $datastream->setContentFromString($with_uuid);
        }
      }
    }
  }
}
